### ISSUE TITLE
Rodeo memory use is at least twice the theoretical requirement

### ISSUE THREAD

**Issue by CAD97** [Kixiron/lasso#4]
(I wrote a [comparison of memory usage of different interners](https://dev.to/cad97/string-interners-in-rust-797). This issue is suggesting some improvements from [my own interner implementation](https://github.com/CAD97/strena) that are the cause of the nearly 3x memory usage difference.) You've quoted memory footprint as a key feature of lasso, so I thought you'd be interested to see my analysis. I've not actually measured performance characteristics of any of these tweaks, just the memory usage patterns.

The current definition of the (single threaded) `Rodeo` is roughly (degenericized)

```rust
struct Rodeo {
    arena: Arena<u8>,
    string_to_spur: HashMap<&'self.arena [u8], Spur>,
    spur_to_string: Vec<&'self.arena [u8]>,
}
```

When using the `raw_entry` API, the size of the `str -> Spur` map can be cut at _least_ to a _third_ by instead storing (effectively) `HashSet<Spur>` (though for `raw_entry` it's a `HashMap<Spur, ()>`) and using `raw_entry` to compare the `Spur` entries _as if_ they were the string they map to. The cost for this memory saving is an extra indirection involved in hashing/comparing entries in the map (for any `str -> Spur` conversions).

There is also a further optimization potential for the `Spur -> str` map. There are two potential options here:

1. Reduce memory usage of the map by about 25%. Instead of storing the `&[u8]` directly in the vector, store indexes into the arena. IIUC, these would minimally be `{ bucket_idx: u32, start_idx: u32, end_idx: u32 }` for the current arena. (In my own crate, it's just `(u32, u32)` as the arena is a single contiguous allocation; however, I believe the less-copies arena approach you have here to probably be significantly better for tail-latency.) The cost would be extra indirection both on `Spur -> str` lookups and on `str -> Spur` lookups if the above change to that map is used.

2. Allow interning of real `&'static str` in the interner without copying them into internal storage. With a direct `Spur -> str` map that doesn't go indirect through the arena, this is trivial to support; just put the `&'static str` into the map. And interning of statically known strings is a surprisingly common and useful thing to be able to do; most contexts that benefit from an interner have some set of known names they know they'll always use and already have baked into the binary's static data section in order to treat them specially. ([Here's rustc's list!](https://github.com/rust-lang/rust/blob/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/librustc_span/symbol.rs#L22-L943))

If lasso can incorporate even just the first size optimization for the `Spur -> str` map, even if just with the hashbrown feature, I'd feel a lot more comfortable recommending lasso instead of maintaining my own interner.

**Comment by CAD97** [comment]
Side note while I'm thinking about it: your `Arena` doesn't do any sort of size doubling; it just allocates new blocks of the same size when necessary. I believe this actually makes interning new strings ***O*(*n*)** (though at a very low factor) if you count allocation as "work", as the number of allocations is linear on the amount of data interned, rather than becoming less frequent and amortizing out.

**Comment by Kixiron** [comment]
Thank you for your interest, it's gotten me back onto in a project that I'd otherwise have left alone! `lasso`'s *main* focus is speed, but when I actually go and think about it, that really isn't the priority here. Winning on benchmarks feels good, but using less memory for your compiler feels the best.

* Great idea on the arena capacity doubling, I'm a wee ashamed that I never thought of doing that
* Storing an index into the arena is another great idea, and fairly simple to implement

The only thing I'm having trouble with is combining things, I went with the indexing strategy right off the bat but now I'm faced with the dilemma of combining it with the `HashSet<Spur>` optimization. Anything I come up with roughly follows this format, which defeats the purpose of even *having* the hash table in the first place

```rust
if let Some(idx) = self
    .strings
    .iter()
    .position(|idx| self.arena.fetch_str(*idx) == string)
{
    K::try_from_usize(idx)
} else {
    let key = K::try_from_usize(self.strings.len())?;
    let idx = self.arena.store_str(string);

    self.strings.push(idx);

    Some(key)
}
```

The main thing I'm having trouble with is *how* to compare a key as if it's a key, keys are just user standins for in index into the `spur_to_string` vector. The only way I can think of doing this is to turn the requested string into a key. This requires searching through the `spur_to_string` vector until you find a matching string or don't. If a string is found, that entry's position is your new key. Otherwise, store the string and tack it onto the vector (This is the code in the above snippet).
Now, this isn't a *bad* solution, it just ends up defeating the speed goal of `lasso` since every insertion (even of preexisting keys) involves a linear search and that's a massive performance drop.

Hopefully I'm missing a really obvious solution with the raw apis, I'll readily admit that I have trouble figuring out what's useful to me there

**Comment by CAD97** [comment]
[Here's how I'm doing it in strena](https://github.com/CAD97/strena/blob/1ddbf48b9f639ffbb4c89b0d51cb005fc0e3a4f7/src/lib.rs#L324-L363):

```rust
#[derive(Clone)]
pub struct Interner<S = ahash::RandomState> {
    hasher: S,
    // SAFETY: symbols must be valid indexes into `symbol_to_span`.
    // `Opaque<Symbol>` is treated in the hashmap as the string it represents.
    string_to_symbol: HashMap<Opaque<Symbol>, (), ()>, // not HashSet so we can use raw_entry API
    // SAFETY: spans must be valid spans in `span_to_string`.
    symbol_to_span: Vec<Span>,
    span_to_string: String,
}

impl<S: BuildHasher> Interner<S> {
    pub fn get_or_insert(&mut self, s: &str) -> Symbol {
        let Interner {
            hasher,
            string_to_symbol,
            symbol_to_span,
            span_to_string,
        } = self;

        let hash = make_hash(hasher, s);
        let entry = string_to_symbol
            .raw_entry_mut()
            .from_hash(hash, |&Opaque(symbol)| {
                let span = unsafe { index_unchecked!(symbol_to_span, symbol.ix()) };
                s == unsafe { index_unchecked!(span_to_string, span.ix()) }
            });

        let (&mut Opaque(symbol), &mut ()) = match entry {
            RawEntryMut::Occupied(entry) => entry.into_key_value(),
            RawEntryMut::Vacant(entry) => {
                let span = insert_substring(span_to_string, s);
                symbol_to_span.push(span);
                let symbol = Symbol {
                    raw: unsafe { NonZeroIdx::new_unchecked(symbol_to_span.len() as Idx) },
                };

                entry.insert_with_hasher(hash, Opaque(symbol), (), |&Opaque(symbol)| {
                    let span = unsafe { index_unchecked!(symbol_to_span, symbol.ix()) };
                    let s = unsafe { index_unchecked!(span_to_string, span.ix()) };
                    make_hash(hasher, s)
                })
            }
        };
        symbol
    }
}
```

(I believe this requires [`RawVacantEntryMut::insert_with_hasher`](https://docs.rs/hashbrown/0.8.0/hashbrown/hash_map/struct.RawVacantEntryMut.html#method.insert_with_hasher) to hash/compare keys indirectly, which is available on hashbrown but not std, which might be where you're falling short.)

To be honest, though, I'm currently thinking it's probably better to allow interning `&'static str` zero-copy rather than reduce the `Span -> str` map size by 25%; after all, the cheapest allocation is one that you don't have to do.

strena uses a single continuous `String` as its allocation, and thus its `Symbol -> Span` map only needs to store `(u32, u32)`, for a 50% save over storing `*const str` (on 64 bit platforms). The main reason strena is implemented like this isn't actually size optimization, though; it's because [it was originally written without any `unsafe` code](https://gist.github.com/CAD97/036c700fad1b4b159421eca089783122)! (Though it uses some unchecked indexing in its current state to eliminate some bounds checks.)

The stepped arena that lasso uses requires at least a `(u32, u32, u32)` to index into, though (unless someone feels like proving that filling up `(u16, u16, u16)` would fill up the address or symbol space first or you put a cap to that size), so the size savings are smaller and eliminate the possibility of interning `&'static str` directly.

**Comment by Kixiron** [comment]
Alright, I incorporated a lot of the improvements you recommended

* Zero-copy static string interning [impl](https://github.com/Kixiron/lasso/blob/master/src/single_threaded.rs#L275-L347)
* Only storing string pointers once ([struct](https://github.com/Kixiron/lasso/blob/master/src/single_threaded.rs#L45-L52), [impl](https://github.com/Kixiron/lasso/blob/master/src/single_threaded.rs#L203-L252))
* Doubling of arena bucket size [impl](https://github.com/Kixiron/lasso/blob/master/src/arena.rs#L77-L81)

The only thing I'm unsure about is [this](https://github.com/Kixiron/lasso/blob/master/src/arena.rs#L57-L73), where I decide which bucket to use for allocation. I'll copy+paste the comment linked because it says it best

> Some space is theoretically wasted here since if a string larger than capacity is interned all other buckets are never looked at again. This could potentially be exploited by interning exponentially larger strings but could be solved by:
> 
> A. Linearly searching every bucket at internment time
> 1. First to last, wasteful but guarantees that we always make the best use possible
> 2. Last to first, hits the most likely buckets first but makes an exceptionally slow slow path
> 
> B. Deallocating excess memory in buckets
> 1. A sweep function that scans all buckets and deallocates extra
> 2. Deallocating the previous bucket's extra memory whenever a new one is created

It's again a tradeoff of speed vs. space, I wanted to get your take on it

**Comment by CAD97** [comment]
What strena does is just use a single continuous arena of `String`. This is obviously the most compact, but it comes with a functionality tradeoff: the already interned strings need to be copied to the new string when reallocating the backing buffer. This cost is amortized, but it definitely impacts tail latency.

Because of the moving as well, the interner itself is _forced_ to store indexes into the buffer rather than direct pointers, as the pointers would become stale every time the backing array reallocates. Similarly, if you try shrinking arena stages when you have to allocate a new one, you'll need to fix up any pointers into that stage to point to the new shrunken allocation.

I think it would be "good enough" to document the degenerate behavior in this edge case (as it's nowhere close to an expected load for an interner), but if you want to try to combat it, one potential idea would be to either

- store up to some N indexes of buckets with significant extra space left. Search those (rather than all) buckets for space to insert the string, or more simply,
- just check the last N buckets for some small fixed N. The cost of checking all of the buckets for space is roughly ***O*(log *n*)**, but ***O*(1)** is better.

And one simple technique I think can mitigate a good chunk of the problem: if an interned string would not fit in the next bucket size, don't increase the bucket size to accommodate it. Instead, just put it in its own perfectly sized bucket and swap it _before_ the currently live bucket. So, _super_ roughly:

```rust
    pub unsafe fn store_str(&mut self, string: &str) -> &'static str {
        let slice = string.as_bytes();
        let len = slice.len();

        if let Some(bucket) = self
            .buckets
            .last_mut()
            .filter(|bucket| bucket.free_elements() >= len)
        {
            return unsafe { bucket.push_slice(slice) };
        }

        let next_capacity = self.capacity.get() * 2;
        if len > next_capacity {
            let bucket = Bucket::with_capacity(len);
            let allocated_string = unsafe { bucket.push_slice(slice) };
            self.buckets.insert(self.buckets.len() - 2, bucket);
            allocated_string
        } else {
            self.capacity = next_capacity;
            let bucket = Bucket::with_capacity(self.capacity);
            let allocated_string = unsafe { bucket.push_slice(slice) };
            self.buckets.push(bucket);
            allocated_string
        }
    }
```

That means that if there's one giant string interned, it only requires space for that one giant string, not twice it.

I also went ahead and measured the current HEAD's memory use with the same harness, and here are the current results:

![with_capacity allocation graph](https://user-images.githubusercontent.com/5992217/87256597-12d4da80-c462-11ea-9d3b-bcf047816ea5.png)

```
     total events | 8
      peak bytes  | 263.8 KB
     ----------------------------
     alloc events | 7
     alloc bytes  | 263.8 KB
     ----------------------------
     freed events | 1
     freed bytes  | 24 B
```

Initial `with_capacity` construction sees three allocations and then a new one on the first insert. I _think_ this is the arena allocating the first bucket; `with_capacity` should probably go ahead and allocate the first bucket initially (though this is quite minor).

![new allocation graph](https://user-images.githubusercontent.com/5992217/87256649-942c6d00-c462-11ea-88e4-e665e10cce2a.png)

     total events | 54
      peak bytes  | 311.4 KB
     ----------------------------
     alloc events | 30
     alloc bytes  | 483.6 KB
     ----------------------------
     freed events | 24
     freed bytes  | 213.1 KB

This definitely looks a lot better than before! `with_capacity` allocation is 45% what it was before, and the `new` allocation is 40% the prior.

**Comment by Kixiron** [comment]
Funnily enough a allocating the initial bucket was on my to-do list, I'm very glad you reminded me!

That's a really elegant solution for the large string problem and I even went and implemented it to a few μs of speed improvement. That aside though, that's a *massive* usage improvement, I'm really blown away by the difference a few relatively small changes make.

I looked into `strena` a little bit and I'm really liking the way you do capacity allocation with the `Capacity` struct, I think I'll add that as well since it could make a massive difference in the efficiency of preallocation

**Comment by Kixiron** [comment]
Alright, I added the last few touch-ups, including pre-allocating a single bucket and the large string bucket swap, I think I'm good to go for 0.3.0 if that's everything covered

**Comment by CAD97** [comment]
I think that's everything involved here! I have a couple more pretty small ideas to try later, along with an open experiment to making a threaded interner version of strena with the same "nearly canonical" design, but that needn't delay publishing these improvements.

The one thing I'd suggest is flipping the polarity of the no-std feature, as features are intended to be purely additive. Instead, make a std feature that's default and can be opted out of via no-default-features.

**Comment by Kixiron** [comment]
I had initially considered that, but the fact that it *added* a dependency that would be there by default really put me off of it

**Comment by CAD97** [comment]
You can just change it to not provide a default hasher on `#![no_std]` mode instead. I think that's fine for those no std folk.

**Comment by Kixiron** [comment]
Hum, I think I'll leave that to another release, I really don't have the willpower to comb through and mess with features today

**Comment by Evrey** [comment]
Back when I wrote a custom allocator for some ancient project, I encountered that very same problem of how to efficiently fill up arena pages that came before the newest one in use.

The solution was stupid simple and fast enough for me, but it *may* have noticeable delays for `lasso`. I maintained an array of arena indices at all times, partitioned by »size classes«. The 0th entry was for the smallest size class, the 1st entry for something twice that size, the 2nd entry for something twice *that* size, etc. I had a maximum, you may stop whereever. So pretty much this:

> store up to some N indexes of buckets with significant extra space left. Search those (rather than all) buckets for space to insert the string, or more simply,

Say your smallest size class is 4 bytes. Then, if an arena page has at most 7 bytes to spare, you store its freespace index into the size class 0 slot. If you feel like it, you can turn that into a skiplist by storing the current index in that slot to the start of the current page's freespace when allocating a new one. That also determins the minimum size class, as it must fit slightly over half an arena index.

The allocation procedure is then:

1. Round the text size down to a size class.
2. Fetch the arena index for that size class.
3. If the index is valid, allocate there.
    - If you do the skiplist thing, fetch the previous arena index from that page's freespace. (A fetch from a memory location, but one you'll write to after all that.)
    - Bump the arena index if there is still enough freespace left for that sizeclass.
    - Move the skiplist index to the new location if you just bumped.
4. If the index is invalid, use the current page as before.

Some things you could do but that would definitely impact allocation latency:

- When you filled up an old page for some size class, check whether the freespace left fits the next-smaller size class. If that's the case, add it to that class' skiplist. This is an `O(n)` operation if you test all smaller size classes.
- When allocating a new page, you could try duplicating the skiplist index throughout the current page's freespace in units of the smallest size class. An `O(n)` memory operation that worsens worst-case latency, but may scratch a few noticeable cycles off the best-case latency, as you don't have to duplicate the skiplist entry every time you bump a size class index.
- When trying to allocate some text, and its size class is full, you could try to fetch the next bigger size class from the freelist before allocating a new page. Doing that exhaustively is again `O(n)`.
- When allocating blocks that aren't exactly size-class-sized, bump the arena index by the exact amount of allocated bytes instead of that size class' bytes. This does not play well with writing an array of skiplist indices. But it will more efficiently fill up your freespace.

However you'd implement that, *if* you'd implement that, these things should be noted:

- Filling up old freespace may still leak a few bytes, namely the size of your smallest size class minus one byte. Even more if you don't do skiplists.
- Not doing the linear probing of adjacent size classes may again leak freespace, given that some identifier lengths are rarer than others.
- However, overall you still leak less memory.

Just a rough implementation plan to give you a better idea. It's fine to say: »Uhh nah, let's not.« After all, it's unclear how well the (slightly or noticeably) increased latency balances out with the potentially lowered leaking of memory and therefore extra amount of pages allocated.

It would be nice to, e.g., attach `lasso` to a Rust lexer, and then run it on individual crates on `crates.io` and also on the entirety of crates on `crates.io` to see how much leaked freespace there actually is in a real-world scenario. And then, if we have these numbers, we may make better decisions on how much latency is worth sacrificing.

**Comment by CAD97** [comment]
The article's been updated with a postscript mentioning the new results, and I think this issue is sufficiently addressed! 🎉
